### ISSUE TITLE
Authorization mechanism not supported

### ISSUE THREAD

**Issue by bjarman** [moviemasher/angular-moviemasher#18]
I just installed the 4.018 stack (in EU-Central/Frankfurt) using the deployment wizard. When I try to upload a movie I get this error:

"<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>37F7E08DBAB4A16D</RequestId><HostId>qw8/AZr4FhE5qe97z3Z0bEnGA0cb9iuNhO59nWadYBsw9O0UJN9p9a7wa+yH09faSaXfnNpBuQw=</HostId></Error>"

What am I doing wrong?

**Comment by syntropo** [comment]
Ugh, you should no longer be getting this error! Which stack did you launch? Have you by chance run PHP composer on the UI and somehow changed the aws-sdk? You might try upgrading it - this library is responsible for providing that signature using the correct mechanism.

**Comment by bjarman** [comment]
I used the 4.018 moviemasher.rb + angular.js stack using my existing EC2 Key Pair.
So, everything at amazon: http://ec2-52-59-97-34.eu-central-1.compute.amazonaws.com/angular-moviemasher/app/

Current user id is i-6a0842d6 should you want to recreate the error.

Any other ideas?

**Comment by syntropo** [comment]
Did you try updating the PHP composer libs on the UI instance? I believe you'd have to install composer to do so.

**Comment by bjarman** [comment]
Nope, I just installed everything as-is?

Should I update stuff - if so how/what?

**Comment by syntropo** [comment]
In config/docker/composer/Dockerfile-composer there are commands that install on Ubuntu, which would have to be rewritten for the Centos that's running on the EC2 LINUX AMI. With that installed, you should be able to cd into the app/php/service/aws directory and run `composer install` to update the aws-sdk libs.

**Comment by bjarman** [comment]
Hi!
We only used the quick start guide on moviemasher.com - are you implying that the quick start guide is wrong?

Would it not be better to push new sources/version - 4.019?

Right now this does not work following the instructions in the quick start.

**Comment by syntropo** [comment]
I don't know that the quick start guide is 'wrong' - it's currently working fine for many folks. The issue you're having is one that was fixed in the last deployment - 4.0.19 contains nothing that would affect it AFAIK. I am not able to test every deployment option for the AMIs in every region and the regions are different, so issues can still arise. The region you're deploying in is relatively new and might have additional constraints that are causing problems. Bottom line is that I have little ability to fix this particular error besides updating the AWS-SDK, so I recommended you try that.

**Comment by bjarman** [comment]
Aha - ok, well, then it would be a good idea to remove regions from the deploy configuriation/quick start. Or at least inform which regions that are untested/which regions that work?

I do not have the time right now to manually configure and test new deploys in other regions so it would be great to know which regions are the "recommended" regions where stuff already is tested.

The "many folks" that this is currently is working for - what region are they using - I will just make a new installation into that region.

We are just aiming for a PoC to show a customer in order to get funds to take the project further.

**Comment by syntropo** [comment]
Everything is tested in the US Standard region. I'm not aware of any problems in other regions besides what you're reporting just now, which I've not had a chance to replicate. It's certainly much easier to fix issues than remove the AMI from particular regions.

**Comment by bjarman** [comment]
Ok, so the US Standard region is the region we will use then. We will cross the bridge of tweaking api versions etc for other regions when we eventually need that. I will let you know if the switch of region solves our current problem so you can close this issue then. Thanks!

**Comment by bjarman** [comment]
...US Standard is not a region. Should we use US East or US West and if US West should we use Oregon or N. California?

**Comment by syntropo** [comment]
AWS refers to us-east-1 as US Standard since it was the first region. 

FYI, I managed to track this problem in eu-central down... Turns out our method of updating the composer components was flawed and the calls to aws-sdk had to be specifically updated to sign requests with version 4. Just pushed a change to angular-moviemasher that fixes this so you should just be able to pull it, though it will take some time to burn a new AMI.
