### ISSUE TITLE
Speeding up mashing of videos

### ISSUE THREAD

**Issue by varungup** [moviemasher/angular-moviemasher#24]
I was trying to mash 4-5 videos into a 8 min video (720p, 2500 bitrate), and it took almost 30 min on c4.large machine. I tried to speed it up by using g2.8xlarge machine and the time to generate the video came down to 5 min.

Is there any other setting I can do to bring the time down to a min or less?

**Comment by syntropo** [comment]
You can try other instance types, though from tests conducted when the g2.8xlarge machines were launched they are the fastest. Otherwise you could potentially reduce the file size of the inputs, or perhaps make sure they are cached on the machine locally. 

On the rendering front, many of the output formatting options can affect the time needed. If you find a particular set of options works well in FFMpeg but cannot be supported in jobs, please post here.
