### ISSUE TITLE
Configured Angular Movie Masher on local with WAMP, After uploading a video file, progress file is not getting created

### ISSUE THREAD

**Issue by harishsalian05** [moviemasher/angular-moviemasher#3]
I get the below response from Import API:

{"completed":0.01,"status":"Queued","ok":1}

Need help to get it working...

**Comment by syntropo** [comment]
That seems to be working, as far as the angular-moviemasher installation is concerned. How have you installed moviemasher.rb? That is the project that can actually process the transcoding job you've queued there.

**Comment by harishsalian05** [comment]
Yes, I have installed moviemasher.rb using boot2docker but the transcoding process doesnt gets started.

**Comment by harishsalian05** [comment]
I have installed boot2docker on windows and following steps provided on https://github.com/moviemasher/angular-moviemasher

**Comment by syntropo** [comment]
What happens if you try to process the queued jobs with just the standard command?

`docker run -d -t --volumes-from=angular --name=moviemasher moviemasher/moviemasher.rb process_loop`

This should just work out of the box because the angular-moviemasher project has already made its directories available. The 'volumes-from' switch is telling moviemasher.rb to go ahead and use them.

**Comment by harishsalian05** [comment]
Issue Resolved!!!

Thanks

**Comment by ibraheemsadiq** [comment]
still not running  after implementing all your discussion , docker container running successfully but localhost shows nothing

**Comment by ibraheemsadiq** [comment]
![screenshot_20180505_054216](https://user-images.githubusercontent.com/6687734/39657993-4e932934-5027-11e8-85cf-a634f39353fc.png)

**Comment by syntropo** [comment]
Well, I'm not sure exactly what you're after, but in your browser you'd want to also supply the port - http://localhost:8080/
