### ISSUE TITLE
Any way to remove a file?

### ISSUE THREAD

**Issue by indigomelody** [moviemasher/angular-moviemasher#32]
I can't seem to find any way of removing a file from the media tray, is this supported / what are some steps to write this code myself?

**Comment by syntropo** [comment]
Sorry, there is no inbuilt mechanism for removing uploaded media. It would be pretty difficult to actual remove the asset because it may be referenced in existing mashes. Typically folks will just flag an asset as 'deleted' without actually removing it from storage to avoid reference errors in existing mashes. To implement this sort of flagging, a new endpoint could be created that simply adds a 'deleted' property to the JSON meta data for the asset, and an adjustment could be made to media.php in order to filter out assets with this property before delivering to the client.
