### ISSUE TITLE
Audio of imported video track

### ISSUE THREAD

**Issue by Themex** [moviemasher/angular-moviemasher#34]
Is that an issue that just an imported video on a selected track is not split on frames track and audio track or it is an unprovided feature?

**Comment by syntropo** [comment]
A clip's audio is not displayed separately in the UI from its video. But the soundtrack of an uploaded video asset is separated into an MP3 file and JPEG image sequence.

**Comment by Themex** [comment]
So, is the solution only bounded by AngularJS implementation? Or should I pay some attention for moviemasher.rb, too?

**Comment by syntropo** [comment]
If you want soundtracks to appear differently in the UI then you'd want to make changes to angular-moviemasher. I don't believe any changes would be needed in either moviemasher.rb or moviemasher.js code.

**Comment by Themex** [comment]
Can you help to find out the simplest way to create audio clip on timeline by video info, pls? I've noticed that dragged video data object contains info about audio (path to it), path of orginal video and of the clip

**Comment by syntropo** [comment]
You'll find there is also a waveform.png file for each soundtrack, residing in the same directory as the original upload. You'd want to draw that somehow in the timeline. It's hard though because it needs to be sized, positioned and cropped along with the video clip as it's transformed. The old version of Movie Masher implemented in Flash used to do this but not enough people seemed to need the functionality for it to be ported to the JavaScript version.

**Comment by Themex** [comment]
That's a bit weird that it has been an unnecessary feautre. Common NLEs like Sony Vegas provide frames and audio split on two linked tracks

**Comment by syntropo** [comment]
Movie Masher is not a common NLE - it's a browser based editor, so audience is expected to be relatively amateur.
