### ISSUE TITLE
i have just got the moviemasher from aws marketplace , so right now i do not know how to make that moviemasher worked in my server , so help me out . it will be better i get all the steps 

### ISSUE THREAD

**Issue by raju11** [moviemasher/angular-moviemasher#4]

**Comment by syntropo** [comment]
Launching in AWS marketplace is not a means for running on your own server. You might try the docker images instead, or attempt to actually install locally using the steps outlined in the Dockerfile.

**Comment by raju11** [comment]
I do have folders in the zipped format ( angular-moviemasher, moviemasher.js,moviemasher.rb) in the website but i do not know which files to unzipped first and will you tell me all the steps on what to do after unzipping a folder

**Comment by syntropo** [comment]
What is the final architecture you're hoping for? Typically just angular-moviemasher (which includes moviemasher.js) is installed on your website and moviemasher.ini is configured to utilize an SQS queue that is polled by the instance(s) of the AMI running in AWS. The idea is to separate the processor intensive transcoding operation from the web hosting and content management functions.

**Comment by raju11** [comment]
I want to use moviemasher so that i can edit the video the uploaded video. So , right now i just want to know the steps on how to make the moviemasher runnable . So will you get me the steps on how to do it ?

**Comment by syntropo** [comment]
Yes, most folks wanting to use Movie Masher want to edit uploaded video. What I'm curious about is the architecture you're hoping to utilize. There is no one set of steps that works for all architectures. Could you describe the relevant computers and existing systems you're hoping to integrate into? Where is it all expected to be hosted?

**Comment by raju11** [comment]
i want to use Movie Masher with php code and i want it to be hosted into AWS 

so i just want to make the movie masher runnable 


will you guide me ?

**Comment by syntropo** [comment]
Those two requirements would seem to be met by simply launching the AWS Marketplace AMI - have you tried that? You can also install just the angular-moviemasher project on another host and use the moviemasher.rb that's installed on the AMI remotely though SQS. If you want to go this route instead, let me know and I can guide you.

**Comment by raju11** [comment]
I did launch Movie Masher from AWS Marketplace AMI and i did unzipped angular-moviemasher-master then put those files into one domain. After that i edit the moviemasher.ini which is in config folder but there then i got stuck 

i need the steps in filling up the empty field in the movimasher.ini and as well as what i have to do at the AWS console 

will you guide me ?? 

I want to save the uploaded files into AWS S3 and also want to used SQS too 

Moreover after editing the file, will i be able to upload files into AWS S3 ?

**Comment by syntropo** [comment]
Okay, great. First step would be to go ahead and create an SQS queue and S3 bucket. You probably also want to create an IAM account and an associated AWS Access Key Pair so access to these resources can be limited for security. In moviemasher.ini you will enter the queue and bucket details as well as both components of the Key Pair, and also setting Client to 'sqs' and File to 's3'. 

In order to get the instance of the AMI to grab the jobs from SQS and be able to upload to S3 it has to be started in a particular way (you cannot change these options on a running instance). Firstly, it should be started under an EC2 'role', which is another element you create in IAM - you'll want to associate the Access Key Pair with this role so it has permissions to interact with both the queue and bucket you've created. Additionally, the instance will be started with User Data, which is simply JSON formatted configuration that minimally includes your queue details:

{"queue_url": "http://queue.amazonaws.com/12345677/queue_name"}

If you're having trouble figuring out the role and permissions, you can also include aws_access_key_id and aws_secret_access_key keys in this JSON, but this isn't as secure. 

Once the instance is started you should be able to upload, render and download normally.
