### ISSUE TITLE
Issues with the docker-compose.yml solution

### ISSUE THREAD

**Issue by ovizii** [moviemasher/angular-moviemasher#51]
Hi there,

I followed the instructions from here: https://hub.docker.com/r/moviemasher/angular-moviemasher/ until the step of "docker-compose up -d" which results in

```
docker-compose up -d
angular_moviemasher is up-to-date
Starting angular_moviemasher_rb ... error

ERROR: for angular_moviemasher_rb  Cannot start service moviemasher_rb: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "config/docker/entrypoint.rb": stat config/docker/entrypoint.rb: no such file or directory: unknown

ERROR: for moviemasher_rb  Cannot start service moviemasher_rb: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "config/docker/entrypoint.rb": stat config/docker/entrypoint.rb: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.

```

what am I missing? Are the instructions under the heading "Docker Usage"  working for anyone else?

**Comment by syntropo** [comment]
Hmmm... did you clone the moviemasher.rb repo to the same directory as angular-moviemasher? You'd need to in order for `docker-compose up -d` to work correctly. You can also try the alternative commands, which just copy the images from Docker Hub. 

FYI, this repo is slated for deprecation, since AngularJS is reaching it's end-of-life in December. There is a new moviemasher.js version (5) coming out soon which modernizes the codebase and introduces a ReactJS implementation. There will eventually be an implementation for a more recent version of Angular, but it could take some months.

**Comment by ovizii** [comment]
hi and thanks for your reply. I only went through steps 1-3, didn't see any mention of copying that other repo. 

I guess I'll wait for the ReactJS implementation then.

![image](https://user-images.githubusercontent.com/837902/127866182-d36c1461-cfbf-434a-b5d5-24014dfbbe5a.png)
